### ISSUE TITLE
Move "try" into a dedicated project

### ISSUE THREAD

**Issue by aurelien-reeves** [cucumber/cucumber-expressions#106]
### 🤔 What's the problem you've observed?

The "try" as part of cucumber-expression javascript implementation oversize it and add a lot of dependency to cucumber-expression itself. It could live on its own, being inside its own repo, or within a dedicated folder within this repo

Refs. https://github.com/cucumber/cucumber-expressions/pull/104#discussion_r845592176

### ✨ Do you have a proposal for making it better?

I would put it its in own repo actually, thus it would not interfere with cucumber-expression at all

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/developer_experience.md)*

**Comment by aslakhellesoy** [comment]
> The "try" as part of cucumber-expression javascript implementation oversize it and add a lot of dependency to cucumber-expression itself.

None of the code from the `try` directory is included in the published npm module. Furthermore, all of the dependencies of `try` are `devDependencies`.

Nevertheless, I agree we should move it out.

**Comment by mpkorstanje** [comment]
Yes, because stuff like https://github.com/cucumber/cucumber-expressions/pull/112 keeps generating notifications.

**Comment by aslakhellesoy** [comment]
Done!

**Comment by mpkorstanje** [comment]
Thanks!
