### ISSUE TITLE
Python release workflow is broken

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-expressions#110]
### 👓 What did you see?

I triggered a release of 15.1.0 and the python release [failed](https://github.com/cucumber/cucumber-expressions/runs/6112743499?check_suite_focus=true)

### ✅ What did you expect to see?

🦄 🌈

**Comment by aslakhellesoy** [comment]
@jsa34 could you have a look at this one please?

**Comment by brasmusson** [comment]
To me it looks like the installation of the poetry installer is missing, something like
```
curl -sSL https://install.python-poetry.org | python -
```
see, https://python-poetry.org/docs/master/#installing-with-the-official-installer

**Comment by brasmusson** [comment]
My impression is that
```
curl -sSL https://install.python-poetry.org | python -
```
needs to be performed before
```
python install-poetry.py -y
```
so that the install-poetry.py has been downloaded.

**Comment by jsa34** [comment]
Indeed - apologies I missed this step... I have just replaced this with a github action to install poetry which should simplify things.  Just created a new MR

**Comment by jsa34** [comment]
Not sure how to verify other than trying to create a release!
