### ISSUE TITLE
java: Not all tests are executed

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/cucumber-expressions#127]
### 🤔 What's the problem you've observed?

https://github.com/cucumber/cucumber-expressions/blob/cc51be8db69b9c780a05e7290eab01d73caf4381/java/src/test/java/io/cucumber/cucumberexpressions/CucumberExpressionTest.java#L39-L44

Because of this not all acceptance tests are executed. This pattern may be repeated elsewhere.

**Comment by aslakhellesoy** [comment]
Good find! Looks like it was changed here: https://github.com/cucumber/cucumber-expressions/commit/c1915d94810615b317e8f59bd3dfd6e6511c3336#diff-5319252eacd59e7b5ff9586220b05ab5843d8542d2b136f9d0d75e85492a05db
