### ISSUE TITLE
Remove Python example illustrating how to define parameter types

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-expressions#142]
### 👓 What did you see?

Instructions about how to define a parameter type in Python: https://github.com/cucumber/cucumber-expressions#python

This is misleading, because Behave has not yet integrated this library into its code. Cucumber Expressions are not supported in Behave.

### ✅ What did you expect to see?

> Behave is not yetusing this library. It doesn't support Cucumber Expressions yet, nor does it have an API for defining parameter types. See https://github.com/behave/behave/issues/968 for more details.

### 📦 Which tool/library version are you using?

Behave [v1.2.7.dev2](https://github.com/behave/behave/releases/tag/v1.2.7.dev2)

**Comment by blaisep** [comment]
possibly a better module than Behave might be `pytest-bdd`
https://pytest-bdd.readthedocs.io/en/latest/#bdd-library-for-the-pytest-runner

**Comment by kieran-ryan** [comment]
Closing as the Python-based [pytest-bdd-ng](https://pytest-bdd-ng.readthedocs.io/en/default/) supports Cucumber Expressions and the documentation is agnostic of frameworks which may or may not decide to adopt it. Happy to reopen if any issue or if raised again however 👍
