### ISSUE TITLE
LICENSE file is empty

### ISSUE THREAD

**Issue by kieran-ryan** [cucumber/cucumber-expressions#250]
The LICENSE file is currently empty; differing from other repositories in the [Cucumber organisation](https://github.com/cucumber).

### 👓 What did you see?

Empty LICENSE file.

### ✅ What did you expect to see?

MIT LICENSE specified, similar to other Cucumber repositories.

**Comment by mpkorstanje** [comment]
Cheers. Fixed in 48d1675847555dedef55587d3f898c861e7aae81.
