### ISSUE TITLE
Request for non-capturing groups in Cucumber Expressions 

### ISSUE THREAD

**Issue by jakimcho** [cucumber/cucumber-expressions#68]
Hello,

It would be nice if Cucumber Expressions support non-capturing groups. 
My intension is to have a mapping for the following step:

`When I order 2 apples`

and the step definitions mapping to be something like that

```
@When("I order {int} [fruit]")
public void orderFruits(int fruitNumber){
........
}
```

Where the square brackets will denote non-capturing group and the expression [{context_description}] would match any text, but wont pass it as a parameter to the step deifinition method

**Comment by aslakhellesoy** [comment]
You can use [alternative text](https://github.com/cucumber/cucumber-expressions#alternative-text) for this, for example:

```
I order {int} apple/pineapple/lychee
```

**Comment by jakimcho** [comment]
Thank you @aslakhellesoy  I guess I can use the alternative text, the problem is that this list with fruites can be realy big and alternative text will get prettie long

**Comment by aslakhellesoy** [comment]
In that case you could define a parameter type for `fruit` add a `fruit` argument to the method signature and simply ignore it. Or you could use regular expressions instead.

I don't think it's worthwhile changing the Cucumber Expressions grammar and parser to support this use case.

**Comment by jakimcho** [comment]
@aslakhellesoy yup this is how I do it, but I hopped for a cleaner way. Thank you!
