### ISSUE TITLE
Terraform Compliance v1.3.31, Alternative text bug?

### ISSUE THREAD

**Issue by j4t1nd3r** [cucumber/cucumber-expressions#86]
### 👓 What did you see?

Alternative text fails in this scenario:
```
Feature: vm compliance

    Scenario: vm Sku compliance
        Given I have azurerm_virtual_machine defined
        Then it must have "vm_size"
        And its value must be Standard_DS1_v2/Standard_DS2_v1
```
Terminal Output:
```
Failure: vm_size property in azurerm_virtual_machine.vm resource does not match with ^Standard_DS1_v2/Standard_DS2_v1$ case insensitive regex. It is set to Standard_DS1_v2.
        And its value must be Standard_DS1_v2/Standard_DS2_v1
          Failure:
```
### ✅ What did you expect to see?

Scenario to pass. 
### 📦 Which version are you using?

Terraform v1.1.7
Terraform Compliance v1.3.31 
PowerShell 7.2.1
Win 11 OS, up to date. 

### 🔬 How could we reproduce it?

1. Install Terraform Compliance v1.3.31 
2.  Extract plan.zip to folder, contains plan file and plan.json and z.feature
[plan.zip](https://github.com/cucumber/cucumber-expressions/files/8245074/plan.zip)

4. Run command 'terraform-compliance -p ./plan -f ./'
5.. See error in terminal output.

**Comment by j4t1nd3r** [comment]
As a workaround. I got a suggestion from a colleague which works:
`Feature: vm compliance

    Scenario: vm Sku compliance
        Given I have azurerm_virtual_machine defined
        Then it must have "vm_size"
        And its value must match the "^(Standard_DS1_v1|Standard_DS1_v2)$" regex`

**Comment by aurelien-reeves** [comment]
I guess there is a misunderstanding of alternative text here.

The alternatives appear in the step definition (in your code), but the step itself (in your feature files) must pick one of the alternatives.

In your case, in your code, you would declare your step definition like that (in javascript for example, but whatever your language, your expression may look like the following):
```javascript
then('its value must be Standard_DS1_v2/Standard_DS2_v1', async function () {
})
```
And in your feature file, you would use it like the following:
```gherkin
Feature: vm compliance

    Scenario: vm Sku compliance
        Given I have azurerm_virtual_machine defined
        Then it must have "vm_size"
        And its value must be Standard_DS1_v2
```
Or
```gherkin
Feature: vm compliance

    Scenario: vm Sku compliance
        Given I have azurerm_virtual_machine defined
        Then it must have "vm_size"
        And its value must be Standard_DS2_v1
```
But not both at the same time. This is the idea of alternative texts: you declare a single step definition but you can use it with several alternatives

**Comment by aurelien-reeves** [comment]
So, I close the issue
But if you think this is a misunderstanding from myself, please, reopen it!

**Comment by j4t1nd3r** [comment]
HI @[aurelien-reeves](https://github.com/aurelien-reeves), I understand what you're saying.

 Is there a way to to use cucumber scenario to check a value against a white list? Such as here I would like to see if vm_size against a white list of allowed  sizes?

**Comment by jenisys** [comment]
@j4t1nd3r
Cucumber is generic. The stuff what you are asking for is from a technical or automation domain.
That would be your step implementation in the Terraform technical domain that provides this implementation.
Because somehow you need to retrieve the `vm_size`. This kind of things are normally provided in step-libraries that are using other technical domain / automation domain library(s) to do the stuff.
Otherwise, the comparison if a value is one of a list of several is normally provided by assert-matchers, like Hamcrest.

**Comment by j4t1nd3r** [comment]
I figured it!

```
Feature: vm compliance

    related resources: azurerm_virtual_machine

    Background: vm resource specific 
        Given I have azurerm_virtual_machine defined

    Scenario Outline: vm Sku compliance
        When it has "vm_size"
        Then it must have "vm_size"
        Then its value will contain one of the following sizes
        | Standard_DS1_v2   |
        | Standard_DS2_v2   |
```

**Comment by j4t1nd3r** [comment]
I did notice I am missing a character in my values for the must not match which I have fixed below. 

You are right, I am not writing any step definitions and working exclusively in feature files. So I will go with the second example you have posted. Thanks.  I will also check out the link.

```
Feature: vm compliance

    related resources: azurerm_virtual_machine

    Background: vm resource specific 
        Given I have azurerm_virtual_machine defined

    Scenario Outline: vm Sku compliance
        Then it must have "vm_size"
        And its value must match the "^Standard_DS*" regex
        And its value must not be <sku>

        Examples:
        | sku                          |
        | Standard_DS4_v2    |
        | Standard_DS5_v2    |
```

**Comment by aurelien-reeves** [comment]
I would actually advice something like this:

```gherkin
Feature: vm compliance

    related resources: azurerm_virtual_machine

    Background: vm resource specific 
        Given I have azurerm_virtual_machine defined

    Scenario: vm Sku compliance
        Then it must have "vm_size"
        And its value must match the "^Standard_DS*" regex
        And its value must not be "Standard_DS4_v2"
        And its value must not be "Standard_DS5_v2"
    
```

**Comment by j4t1nd3r** [comment]
Thnx. I will be adapting both methods depending on the use case!
