### ISSUE TITLE
Typescript step definition not matched

### ISSUE THREAD

**Issue by alphadijkstra** [cucumber/cucumber-expressions#93]
### 👓 What did you see?

Creating step definitions like below are not matched to the feature.
It works when making it a regular expression (instead of cucumber expression) as mentioned in [Docs](https://github.com/cucumber/cucumber-expressions/blob/main/java/heuristics.adoc).

### ✅ What did you expect to see?

Step definitions should be matched correctly to the feature without having to use a regular expression.

### 📦 Which tool/library version are you using?

WebdriverIO 7.16.13
Cucumber 7.3.2
Cucumber-expressions 15.0.2
TypeScript 4.5.5

### 🔬 How could we reproduce it?
**Not working:**
```
Given("The user selects {string} from the (country|language) dropdown", function(toBeSelectedValue: string, dropdownType: string){
    console.log(toBeSelectedValue)
    console.log(dropdownType)
})
```
**Working:**
```
Given(/^The user selects (.*) from the (country|hospital) dropdown$/, function(toBeSelectedValue: string, dropdownType: string){
    console.log(toBeSelectedValue)
    console.log(dropdownType)
})
```
**Feature file:**
```
Feature: Select dropdown value

Scenario: A value is selected
    Given The user selects "Norway" from the country dropdown
```

**Comment by aurelien-reeves** [comment]
Could you please also post the step used inside a feature, and the regular expression that works?

**Comment by alphadijkstra** [comment]
> Could you please also post the step used inside a feature, and the regular expression that works?

Updated it :)

**Comment by aurelien-reeves** [comment]
thank you.

So actually, the correct cucumber expression is: "The user selects {string} from the country/language dropdown"

Alternatives in cucumber expression are simply expressed with the single "/". The pipe "|" is used when defining parameter types

**Comment by alphadijkstra** [comment]
Can't believe I overlooked that. Even after re-reading the documentation multiple times...

Thank you so much! It works now.

**Comment by aurelien-reeves** [comment]
What in the doc led you into that error?
Do you think we can improve it somehow?
